In [13]:
x = [x for x in range(1,6)]
print(x)

[1, 2, 3, 4, 5]


- **Shift+Enter ile çalıştır ve bir sonraki hücreye geç:**
- **Ctrl+Enter ile çalıştır ve mevcut hücrede kal:**
- **A ile başa, B ile sonrasında hücre ekle:**
- **DD yazarak hücreyi sil:**
- **Z yazarak geri al:**

In [3]:
import numpy as np
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


- **Numpy verileri tek tip olarak karşımıza çıkar**
- **eğer listede float varsa tüm intleri float'a çevirir çünkü float daha genel bir tiptir**
- **str olan veri tipi bulunan bir veri setindeki tüm verileri str türüne çevirir**
- **Özellikle çevirmek istiyorsak da alttaki gibi yapmalıyız**
- **stringi integere çeviremiyoruz tabii ki**
- **eğer string değerimiz "4.2" gibi bir değerse önce float sonra inte çevirebiliriz**


In [6]:
import numpy as np
x = np.array([1,2,3,5.3], dtype="int32")
print(x)

[1 2 3 5]


In [12]:
import numpy as np
m = np.zeros(10,dtype="int32") #Elemanları 0 dan oluşan array yaratmak
n = np.zeros((3,4), dtype="int32") #Derinlik katmak için (x,y) x row y column
p = np.zeros((3,4,5), dtype="int32") # 3 tane 4e 5lik
print(m)
print(n)
print(p)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [18]:
np.zeros((2,3), dtype="str") #Str tipinde iken boşluklar üretir, bool tipinde de False üretir çünkü 0 false'dır

array([['', '', ''],
       ['', '', '']], dtype='<U1')

<h1>Belirli elemanlardan array oluşturmak</h1>

In [8]:
import numpy as np
a= np.full((2,3),5) #sağda belirttiğimiz değer "a" gibi str bir değer de olabilirdi.
b= np.full(4,5) #bir belirteç koymaığımızda da 4 adet 5 üreten bir sisteme sahip
print(a)
print(b)

[[5 5 5]
 [5 5 5]]
[5 5 5 5]


<h1>Ardışık sayılardan array oluşturmak</h1>

In [10]:
np.arange(0,12,) #12 dahil değil

array([0, 3, 6, 9])

In [12]:
np.arange(0,16,5) #artış sayısını da son parametre ile belirtebiliriz

array([ 0,  5, 10, 15])

In [4]:
import numpy as np
np.arange(12,2,-2) #başlangıçtaki sayı diğerinden küçükse negatif olarak o sayıya ulaşamayacağı için boş array döndürür

array([12, 10,  8,  6,  4])

<h1>Aralığı eşit olarak bölmek</h1>

In [16]:
np.linspace(1,5) #1 ve 5 dahil olmak üzere 50 adet eşit parça çıkaracak

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [18]:
np.linspace(1,5,num=3) #kaç adet bölüm çıkaracağını da bu parametre ile çıkarabiliyoruz.

array([1., 3., 5.])

<h1>Normal dağılımdan örneklem almak</h1>
- (ortalama, standart sapma, array boyutu)

In [19]:
np.random.normal(0,100,(4,5)) #ortalaması 0 standart sapması 100 olan bir örneklemden 4,5 boyutunda sayılar çıkaracak

array([[-124.31851402, -238.54052915,  -88.02260204,  -79.03217113,
          15.80471818],
       [  -2.74586083,   86.22530066,  -92.67458725,   81.94897434,
         -32.26177144],
       [  73.03500887,   59.94689946,  113.93365696, -156.94631933,
         109.24746159],
       [  95.02660625, -148.8773248 ,  -93.31364031,  -19.4270567 ,
         140.86330067]])

<h1>Random sayılardan array oluşturmak</h1>

In [21]:
np.random.randint(1,10,(3,4)) #1 ile 9 arasında 3,4lük array (yine son sayı dahil değil)

array([[6, 7, 4, 2],
       [4, 3, 4, 1],
       [9, 3, 2, 2]])

<h1>Birim matris oluşturmak</h1>

In [22]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

- **Listeler birbirleri ile operate edilemezken numpy arrayleri edilebilir**
- **eleman bazlı olarak çarpma toplama işlemleri yapılabilir.**

In [27]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x+y)
print(x*3)
#Eleman sayısı aynı olmalıdır

[ 6  8 10 12]
[ 3  6  9 12]


<h1>Reshape</h1>
reshape edilen size ile dönüştürülen size eşit olmalı. 10 birimi (2,6) olarak dönüştüremeyiz mesela


In [35]:
a = np.arange(1,11)
a.reshape(2,5) #tek boyuttan 2ye 5lik bir arraye dönüştürdük

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
a = np.arange(1,21)
a.reshape(-1,4) #-1 burada x gibi. yani 4 ile hangi sayı bunu resahpe eder onu python'a bırakıyoruz kendi buluyor

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

<h1>CONCATENTAION</h1>
Arrayleri birbirine eklemek
Farklı dtype'a sahip arrayler eklenirken hepsi bir türe dönüşür

In [40]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = (11,12)
np.concatenate([a,b,c])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12])

<h1>SPLITTING</h1>


- **verilen index değerleri için bir aralık oluşturup oradan bölüyor tüm array'i. Listelerde de çalışır**

In [8]:
import numpy as np
a = np.arange(0,21)
np.split(a,[5,9])

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])]

In [11]:
a=np.arange(20).reshape(5,4)
np.vsplit(a,[2,3]) #vertical veya horizonal split yapılabilir. Burada vertical olarak böldük. Netten ekstra örneklere bakarsın

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

<h1>SORT</h1>

In [13]:
a = np.array([23,12,34,56,76,12,3,4,34])
np.sort(a)

array([ 3,  4, 12, 12, 23, 34, 34, 56, 76])

In [14]:
a

array([23, 12, 34, 56, 76, 12,  3,  4, 34])

In [17]:
a.sort()  #a verisini güncelledi diğerinde yalnızca np.sort(a) yaptığızda sıralı veriyordu

In [16]:
a


array([ 3,  4, 12, 12, 23, 34, 34, 56, 76])

<h1>MULTIDIMENTONAL INDEXLERE ULAŞMA</h1>

In [29]:
x = np.arange(1,41).reshape(4,10)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [31]:
x = np.arange(1,41).reshape(4,10)
x[1,3]    #[1. index yani 2. rowdaki 3.index yani 4. elemanı getirdi

14

In [34]:
a=np.arange(1,13).reshape(3,4)
a[::1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
a=np.arange(1,13).reshape(3,4)
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

- **spesifik belirterek de indexleme yapabiliriz**

In [42]:
x=np.arange(1,13)
indexler = [2,3,6]
x[indexler]

array([3, 4, 7])

In [5]:
for i in range(20):
    print("seni seviyorum kerem")

seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem
seni seviyorum kerem


<h1>Filtreleme ve toplama</h1>

In [50]:
x=np.arange(-5,3).reshape(2,4)
x[x<0]

array([-5, -4, -3, -2, -1])

In [54]:
a = np.arange(0,11)
filt= a>3
filt
#koşulu sağlayanlar için true diğerleri için false döndürdü

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [56]:
x=np.arange(-5,3)
np.sum(x<0) #burada da aslında koşula uyan kaç değer olduğunu görüyoruz çünkü true'ları sayıyor

5

In [58]:
x=np.arange(-5,3)
np.sum(x) #bu da basitçe toplama işlemi

-12

In [59]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

- **Axis 1 yani rowlara bakıyor. İlk rowda hepsi 8den küçük yani false. Aynı şekilde 2. row da öyle**
- **.all metodu true false olarak çalışır ve tüm veriyi analiz eder. 2. satırda 8den büyük değerler vardı ama tüm rowu kaplamıyordu**

In [60]:
np.all(a>8,axis=1) 

array([False, False,  True,  True])

- **np.all yerine np.any kullandığımızda bir true varsa o zaman hepsini true döndürüyor. all a çok benziyor**


In [62]:
np.any(a>8,axis=1)

array([False,  True,  True,  True])